### ISSUE TITLE
Scaler errors

### ISSUE THREAD

**Issue by zervin** [DrLex0/DualstrusionPostproc#1]
Latest version of  slic3r was barking at the dual script with errors like below.

Experimental push on scalar is now forbidden at /home/user/dualstrusion-postproc.pl line 699, near "))"
Experimental push on scalar is now forbidden at /home/user/dualstrusion-postproc.pl line 703, near "))"
Experimental push on scalar is now forbidden at /home/user/dualstrusion-postproc.pl line 721, near "])"
Experimental push on scalar is now forbidden at /home/user/dualstrusion-postproc.pl line 722, near "$fanSpeed)"

Swapped out all of the push lines in the half dozen places it complained about with the suggested push format and it stopped complaining.

push $rohanRoot->{'rohan2'}, $rohan1;
to
push @{ $rohanRoot->{'rohan2'} }, $rohan1;

**Comment by DrLex0** [comment]
Should be fixed in current source.
