### ISSUE TITLE
Extruding before Extruding

### ISSUE THREAD

**Issue by PMARINA** [DrLex0/DualstrusionPostproc#4]
**Describe the bug**
With certain models and configurations, the first extruder to print will heat to the printing temperature, while the secondary extruder will only heat to 140 C. Then, the printer will attempt to print with the second extruder when it should, albeit before it builds the tower, or heats to the printing temperature.

**Environment**
Your OS and the version of Slic3r the issue is encountered with and if relevant, the version of your Perl runtime (try `perl --version`). 

Windows 10
PrusaSlicer 2.0.0
Perl 5.26.1 for linux x86_64-linux-gnu-thread-multi

Mind that bugs with alpha releases of Slic3r should probably not be filed. Wait at least until the next beta release.

**To Reproduce**
Steps to reproduce the behavior. If relevant, attach STL file(s) and Slic3r config as a ZIP archive.
Can't attach the files or configuration that created this behavior but will update if I can find other files that produce the same behavior.

**Comment by DrLex0** [comment]
This is a known issue and of course I forgot to mention this in the README, it is only in comments in the script itself. The script currently requires that there is something in layer 1 (on the build plate) that is printed with the right extruder (T0). Two possible workarounds until this is fixed:
* Swap your filaments such that the filament for the object touching the build plate is in the right extruder.
* Add an extra object and assign it to the right extruder (‘1’ in PrusaSlicer). To avoid wasting too much time and material, use something tiny that is only 1 layer thick.

**Comment by DrLex0** [comment]
This should now be fixed in release v1.0, together with some other bugs.
Because the script now inserts its own start G-code, it is no longer required to use the custom ‘postproc’ start G-code. If you replace it with the regular Start-dual-extruders.gcode, you must also update `make_fcp_x3g`.
