### ISSUE TITLE
Wrong Extruder Used on Second Layer

### ISSUE THREAD

**Issue by sah1376** [DrLex0/DualstrusionPostproc#5]
**Describe the bug**
Bottom half of print is supposed to be only nozzle 1 and top half only nozzle 2. First layer is printed correctly but then nozzle 2 is used for second layer, without preheating, then it goes back to using nozzle 1 for the rest of the first half of the job, tool changes to nozzle 2 for top half of print, but doesn't preheat.

Prints using both nozzles on the first layer tool change and preheat correctly.

Prints are also out of position on the bed, 30-40mm to the left of centre, only while dual extruding.

**Environment**
Kubuntu16.04 using PrusaSlicer 2.0.0

**Comment by DrLex0** [comment]
I cannot reproduce this.
Are you using the latest version of the script (1.0)?
Please attach the project file (3MF) and the gcode file as produced by the script.

**Comment by sah1376** [comment]
Hi, thanks for the fast response!

Updated gcode snippets, dualstrusionpostproc and make_fcp_x3g again today just to make sure.

Attached a zip with the files.


[3d Print Stuff.zip](https://github.com/DrLex0/DualstrusionPostproc/files/3487827/3d.Print.Stuff.zip)

**Comment by DrLex0** [comment]
Can you send the .gcode file instead of the .x3g?

**Comment by sah1376** [comment]
[Thin_Butterfly.gcode.zip](https://github.com/DrLex0/DualstrusionPostproc/files/3487876/Thin_Butterfly.gcode.zip)

Sorry, right file this time.

**Comment by DrLex0** [comment]
There is no difference between your .gcode file and what I get here as output, and the file does not have any commands to swap tools until the 3.05mm layer. Your X3G file however is very different and contains tool change commands at inappropriate places. This must mean your version of GPX is to blame here.
What version of GPX are you using? Is it some kind of custom build? Have you changed the value of `MACHINE` in `make_fcp_x3g`?

**Comment by sah1376** [comment]
I'm using GPX version 2.0-alpha, from the repo.

I have changed the machine type to 'r1d' as 'fcp' didn't show up when I ran gpx -?, as per the instructions in the make_fcp_x3g file.

**Comment by DrLex0** [comment]
There is a whole plethora of versions and builds, and 2.0-alpha is pretty ancient and seems to be full of bugs. Ubuntu 18.04 has version 2.5.2 which is the latest one available [from here](https://github.com/markwal/GPX/releases). You might be able to install this in 16.04 through xenial-backports. If not, uninstall your current package and manually install the 2.5.2 binary from that [GitHub release page](https://github.com/markwal/GPX/releases), or build it from the sources.

**Comment by sah1376** [comment]
Installed gpx 2.5.3 and the problems seem to have been fixed! No incorrect tool changes and the position is correct on the bed too.

Thank you for your help and for all the work you have put into this project!

**Comment by DrLex0** [comment]
Glad to hear it works!
